// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1W3KaL4TRPf5dWAttJeVGa4RERXJP94o',
    appId: '1:300760354070:web:30fadafebcacca8e1c5437',
    messagingSenderId: '300760354070',
    projectId: 'niri9-c2612',
    authDomain: 'niri9-c2612.firebaseapp.com',
    databaseURL: 'https://niri9-c2612-default-rtdb.firebaseio.com',
    storageBucket: 'niri9-c2612.appspot.com',
    measurementId: 'G-LSCG90H47Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJbNMXvoQX1JlYEQ5EpL3rGv2Tb6wDSRw',
    appId: '1:300760354070:android:e2086c9a9609e0f61c5437',
    messagingSenderId: '300760354070',
    projectId: 'niri9-c2612',
    databaseURL: 'https://niri9-c2612-default-rtdb.firebaseio.com',
    storageBucket: 'niri9-c2612.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGmHWsb62v-pz-l4qKzekkO6i5kFpoAKs',
    appId: '1:300760354070:ios:a2c12c6ec530fac71c5437',
    messagingSenderId: '300760354070',
    projectId: 'niri9-c2612',
    databaseURL: 'https://niri9-c2612-default-rtdb.firebaseio.com',
    storageBucket: 'niri9-c2612.appspot.com',
    androidClientId: '300760354070-i35oqbo6ht75f9i3i96lq641b31pme5g.apps.googleusercontent.com',
    iosClientId: '300760354070-b79ompmq51gb1lme7oi13flcnr9lhf9j.apps.googleusercontent.com',
    iosBundleId: 'com.niri.niri9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGmHWsb62v-pz-l4qKzekkO6i5kFpoAKs',
    appId: '1:300760354070:ios:a2c12c6ec530fac71c5437',
    messagingSenderId: '300760354070',
    projectId: 'niri9-c2612',
    databaseURL: 'https://niri9-c2612-default-rtdb.firebaseio.com',
    storageBucket: 'niri9-c2612.appspot.com',
    androidClientId: '300760354070-i35oqbo6ht75f9i3i96lq641b31pme5g.apps.googleusercontent.com',
    iosClientId: '300760354070-b79ompmq51gb1lme7oi13flcnr9lhf9j.apps.googleusercontent.com',
    iosBundleId: 'com.niri.niri9',
  );
}
